### ISSUE TITLE
coder serve hangs trying to find tunnel

### ISSUE THREAD

**Issue by MichaelSitter** [coder/coder#4593]
Hey team, I'm trying to follow the docker quickstart guide but i'm getting blocked on the first step running `coder server`:

```
Coder v0.9.10+574e5d3 - Remote development on your infrastucture
Using built-in PostgreSQL (/Users/michaelsitter/Library/Application Support/coderv2/postgres)
Opening tunnel so workspaces can connect to your deployment. For production scenarios, specify an external access URL
🌎 Finding the closest tunnel region...
```

The tool just spins indefinitely here. My understanding is the only pre-reqs are a running Docker daemon, is there something else I'm missing?

**Comment by kylecarbs** [comment]
[This](https://github.com/coder/coder/pull/4592) should fix the hanging to report a better error... but I believe you aren't able to access our tunnel servers for some reason.

Can you manually access `pit-1.try.coder.app`?

**Comment by MichaelSitter** [comment]
hey @kylecarbs! I hit that in a browser & it responds with page containing just the text `https://coder.com`. In a separate terminal session I tried `coder login http://localhost:3000`, but I'm still seeing `build info: do: Get "http://localhost:3000/api/v2/buildinfo": context deadline exceeded`.
One thing i've been struggling with is once I'm in this state I can kill the coder process, but postgres stays up and I can't re-run `coder serve`, it says `process already listening on port 49740`. Is there a way I can re-attach to the running db? Or force coder to recycle it?

**Comment by kylecarbs** [comment]
That in entirety is *very* strange behavior. You can do a hard reset by removing the configuration folder.

```
rm -rf /Users/michaelsitter/Library/Application Support/coderv2/postgres)
```

**Comment by MichaelSitter** [comment]
After upgrading to Coder to v0.10.1 I was finally able to get `serve` to connect. My peer was successful with a clean install too, so I think we can probably close this.
