### ISSUE TITLE
Quickstart Docker on macOS

### ISSUE THREAD

**Issue by fex01** [coder/coder#5263]
Hi guys,

According to [quickstart/docker](https://coder.com/docs/coder-oss/latest/quickstart/docker) it should be possible to get started with macOS & docker. Which I would really appreciate to get a first look of what coder is and how I could use it.

Sadly the docu seems to be Linux specific - for example `export DOCKER_GROUP=$(getent group docker | cut -d: -f3)` will not help me under macOS.
And running the docker command without `--group-add $DOCKER_GROUP` will net me the error `Error pinging Docker server: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock:` in step `coder templates create`. Same result when trying the docker-compose approach.
Yes in the troubleshooting section is a link to [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) - which does not really help under macOS...

How would I get started with a coder docker deployment under macOS? 

Sorry for the noob questions,
Felix

**Comment by ghuntley** [comment]
Hey Felix;  Argh, indeed our documentation is incorrect apologies for time wasted and thanks for opening the GitHub issue to discuss.

> Sadly the docu seems to be Linux specific - for example `export DOCKER_GROUP=$(getent group docker | cut -d: -f3)` will not help me under macOS.

`DOCKER_GROUP` can be omitted on macOS  and potentially on Linux (need to test/discuss with Maf) and our docs need updating.

> And running the docker command without `--group-add $DOCKER_GROUP` will net me the error `Error pinging Docker server: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock:` in step `coder templates create`. Same result when trying the docker-compose approach.

The `unix:///var/run/docker.sock` socket won't appear until the Docker Desktop.app application is running.

![CleanShot 2022-12-05 at 14 45 00@2x](https://user-images.githubusercontent.com/127353/205551461-fde556a4-7d45-49b8-83c7-dcd9080742ed.png)

```shell
export CODER_DATA=$HOME/.config/coderv2-docker
mkdir -p $CODER_DATA
docker run --rm -it \
    -v $CODER_DATA:/home/coder/.config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    ghcr.io/coder/coder:latest

Coder v0.13.1+9e80322 - Software development on your infrastucture
Using built-in PostgreSQL (/home/coder/.config/coderv2/postgres)
Opening tunnel so workspaces can connect to your deployment. For production scenarios, specify an external access URL

View the Web UI: https://fccae4bbcf514bfdfd4cba214fc9f58f.pit-1.try.coder.app
2022-12-05 04:44:16.471 [INFO]  (coderd.update_checker) <./coderd/updatecheck/updatecheck.go:147>       (*Checker).start        time until next update check    {"duration": "23h38m36.00361067s"}

Get started by creating the first user (in a new terminal):
 coder login https://fccae4bbcf514bfdfd4cba214fc9f58f.pit-1.try.coder.app 

==> Logs will stream in below (press ctrl+c to gracefully exit):
```

Lemme know how you go!

**Comment by fex01** [comment]
@ghuntley thanks for the positiv reply :-)

> The unix:///var/run/docker.sock socket won't appear until the Docker Desktop.app application is running.

Yes, Docker Desktop is running - otherwise I would have trouble with the command `docker run` :-)

To be more precise - these are the exact steps I do until I fail:

```bash
export CODER_DATA=$HOME/.config/coderv2-docker
mkdir -p $CODER_DATA
docker run --rm -it \
    -v $CODER_DATA:/home/coder/.config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    ghcr.io/coder/coder:latest
```

- switch to second shell
- `curl -L https://coder.com/install.sh | sh`
- `coder login https://fccae198638869dfceda5f8c61a53064.pit-1.try.coder.app` - (url from docker shell output)
- `coder templates init`
  - `Develop in Docker`
- `cd ./docker`
- `coder templates create`
  - _Create and upload "~/repos/coder/docker"?_ - `yes`

Everything until the last step is successful - output from the last step is:

```
> Create and upload "~/repos/coder/docker"? (yes/no) yes
✔ Queued [10ms]
✔ Running [4ms]
✔ Adding README.md... [-1ms]
✔ Setting up [59ms]
✔ Parsing template parameters [121ms]
⧗  Detecting persistent resources
  Terraform 1.3.4
  data.coder_workspace.me: Refreshing...
  data.coder_provisioner.me: Refreshing...
  data.coder_provisioner.me: Refresh complete after 0s [id=73210ad1-d16a-4d72-bd95-b4c40cc6eb03]
  data.coder_workspace.me: Refresh complete after 0s [id=39d7371a-1356-4a06-be56-b73858586eb0]
  Error: Error pinging Docker server: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied

✔ Detecting persistent resources [920ms]
✘ Cleaning Up [107ms]
template import provision for start: recv import provision: plan terraform: terraform plan: exit status 1
Run 'coder templates create --help' for usage.
```

**Comment by fex01** [comment]
Follow up - no idea if that is relevant, but:
- when directly using terraform, for example in the [terraform docker tutorial](https://developer.hashicorp.com/terraform/tutorials/docker-get-started/docker-build), I have no issues
- also docker in docker scenarios run without trouble - for example in this [little playground project](https://github.com/fex01/dockerized-tf-tools)

**Comment by mafredri** [comment]
Thanks for reporting and providing all the follow up details @fex01.

The problem with macOS is that the Docker socket is not what it appears to be:

```console
❯ ls -lha /var/run/docker.sock /Users/maf/.docker/run/docker.sock
lrwxr-xr-x  1 root  daemon    34B Nov 25 17:08 /var/run/docker.sock@ -> /Users/maf/.docker/run/docker.sock
srwxr-xr-x  1 maf   staff      0B Dec  5 11:12 /Users/maf/.docker/run/docker.sock=

❯ stty -echo -icanon && nc -U ~/Library/Containers/com.docker.docker/Data/debug-shell.sock && stty sane
/ # ls -lha /var/run/docker.sock /run/guest-services/docker.sock
lrwxrwxrwx    1 root     root          31 Dec  5 09:12 /var/run/docker.sock -> /run/guest-services/docker.sock
srw-rw----    1 root     root           0 Dec  5 09:12 /run/guest-services/docker.sock
```

What's actually being forwarded to the container is `/run/guest-services/docker.sock` from inside the Docker VM. And it's permissions are `root:root` only. Our options are to 1) change it's permissions, or 2) run the docker container as root.

Option 2) introduces yet another problem, embedded Postgres does not want to run as root.

```
❯ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock --name coder --user root ghcr.io/coder/coder:latest
Coder v0.13.1+9e80322 - Software development on your infrastucture
Using built-in PostgreSQL (/home/coder/.config/coderv2/postgres)
The built-in PostgreSQL cannot run as the root user. Create a non-root user and run again!
Run 'coder server --help' for usage.
```

One thing that a user _can_ do, is to start Coder:
```
❯ docker run -it --rm -d -v /var/run/docker.sock:/var/run/docker.sock --name coder ghcr.io/coder/coder:latest
```

And then update the socket permission:

```
❯ docker exec -it --user root coder chgrp 1000 /var/run/docker.sock
```

But this permission change will propagate to all containers that have access to the socket. Likewise on Linux, this change will propagate to the host machine, giving user `1000` permission to do anything with the Docker daemon.

So I don't see a great solution. Modifying socket permissions is iffy, and should only be done with full understanding of the security ramifications. Perhaps giving users the option to run as root would be the best way forward, and allowing embedded postgres to either run as root or be started as a user with lesser permissions.

**Comment by fex01** [comment]
@mafredri first of - thank you very much for the detailed and interesting explanation.

My summery would be that it is currently not really recommendable to run coder on macOS (via Docker)? But for evaluation purpose, keeping in mind the risk of running a container with permissions to manipulate `/var/run/docker.sock`, it might be an option?

Just to make sure that my understanding is correct - `docker exec -it --user root coder chgrp 1000 /var/run/docker.sock` would change permissions inside the coder container. After deleting the container there would be no lingering security impact to the host system, correct?

**Comment by mafredri** [comment]
> Just to make sure that my understanding is correct - `docker exec -it --user root coder chgrp 1000 /var/run/docker.sock` would change permissions inside the coder container. After deleting the container there would be no lingering security impact to the host system, correct?

No, unfortunately not. This permission change would stick around even after deleting the container.

In the case of macOS, restarting the Docker daemon would reset the permission change, though.

> So what is happening here?

Ah, it seems you also need to do `docker exec -it --user root coder chmod g+w` to make the socket group writable (sorry, I missed that this was missing as I was testing the solution).

**Comment by fex01** [comment]
Okay, I now I'm a little bit proud that I found the second roadblock myself 😅 Looking at the `ls -al` output, I noticed that there is no write permission for the group. That can be changed with `docker exec -it --user root $CONTAINER_ID ls -al /var/run/docker.sock`.  
And now the error is finally gone and I can progress with the "Quickstart" :-)

On that note - might be a good idea to mention these points in the docu - or to remove the comment that coder via docker can be deployed on macOS? 🤔

**Comment by mafredri** [comment]
Nice work @fex01! Is it OK if I keep this issue open until we've fixed the user story for macOS? Either we'll fix the documentation to explain all the steps or, if possible, improve the Docker container 👍🏻.

**Comment by mafredri** [comment]
Here is one proposal for how the instructions would look for macOS:

```
export DOCKER_GROUP=666
export CODER_DATA=$HOME/.config/coderv2-docker

# Since Coder runs as non-root, we must ensure that the docker.sock is
# accessible to the coder user.
# WARNING: This permission change will reset if Docker Desktop is
# restarted. Note that the permission change will apply to all other
# containers as well, if you are sharing the docker.sock with them.
docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --user root \
    --entrypoint /bin/sh \
    ghcr.io/coder/coder:latest \
    -c "chmod g+w /var/run/docker.sock && chgrp $DOCKER_GROUP /var/run/docker.sock"

mkdir -p $CODER_DATA
docker run --rm -it \
    -v $CODER_DATA:/home/coder/.config \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --group-add $DOCKER_GROUP \
    ghcr.io/coder/coder:latest
```

This is very convoluted, though. Still considering alternative options.

**Comment by matifali** [comment]
@bpmct de we have this in our docs?

**Comment by bpmct** [comment]
Yeah, we added a little warning. We still don't have a fantastic solution for Docker on macOS so we recommend using the binary. 

![Screenshot 2023-05-08 at 8 41 47 AM](https://user-images.githubusercontent.com/22407953/236839674-8ee3d029-3706-484e-92da-3d2293aa5a0b.png)

**Comment by matifali** [comment]
Quickstart has moved to https://coder.com/docs/v2/latest/install/docker, and we do not recommend using docker with Mac now.

Closing.

**Comment by bpmct** [comment]
I ended up solving it in my project with a special entrypoin that detects if the user is root and does special stuff

https://github.com/coder/portable-coder#sharing-docker-socket-on-macos

https://github.com/coder/portable-coder/blob/9ccdcfb2a965d7e619ead195cedd88cb9871f817/build/scripts/entrypoint.sh#L58-L71
