### ISSUE TITLE
Handle Kubernetes Pod provision failure due to resource constraints

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#5783]
Due to having finite resources available in a Kubernetes Cluster there's scenarios where users try to provision a workspace and the pod sits in pending state.

The pod sits in pending state forever and the terraform eventually bombs out with context deadline exceeded and the workspace going into failed state.

- Is there plans to provide a preflight check so it blocks the user from provisioning?
- Is there something we can interface with coder to signal resource constraint issue during workspace creation?
- How can we auto cleanup failed workspaces from Coder so the pod does not sit in pending forever?

**Comment by kylecarbs** [comment]
An interesting problem here... this might be better solved by interfacing directly with the Kubernetes API instead, and maybe leads to #5321.

It's difficult to surface _good_ error messages with Terraform because there are so many scenarios.

Would y'all maintain a custom provisioner if it was some very basic JavaScript like:

```
const k8s = require('k8s');

const kubeconfig = {
  apiVersion: 'v1',
  kind: 'Pod',
  metadata: {
    name: 'my-pod'
  },
  spec: {
    containers: [{
      name: 'my-container',
      image: 'nginx:latest'
    }]
  }
};

const k8sApi = k8s.api({
  endpoint: 'http://localhost:8080',
  auth: {
    bearer: 'YOUR_BEARER_TOKEN'
  }
});

k8sApi.post('/api/v1/namespaces/default/pods', kubeconfig, (err, res) => {
  if (err) {
    console.log(`Error: ${err}`);
  } else {
    console.log(`Pod created: ${res}`);
  }
});
```

We'd likely maintain a set of helpers that would make this easier, or use Pulumi which would entirely automate most of that scaffold code away.

**Comment by dcarrion87** [comment]
Hmmm thanks @kylecarbs we'll have a think about it some more.

The other thing is being able to do preflight checks to attempt to block a user before they press button or command.

**Comment by kylecarbs** [comment]
@dcarrion87 we now have an endpoint that can be used to send custom startup logs for a pod. While this might not be ideal for your case, you could jank together a way to ship Kubernetes events. Curious for your thoughts

**Comment by dcarrion87** [comment]
@kylecarbs not 100% certain what you mean by this. Is there a link with an example or doc?

This is still a problem for us and we're still thinking of ways of solving without creating too much tech debt.

**Comment by bpmct** [comment]
Closing as duplicate of #7576
